### ISSUE TITLE
vm in controller 

### ISSUE THREAD

**Issue by httpete-ire** [andyjessop/angular-starter#1]
nice work on this, according to the style guide the context of 'this' in a controller [section](https://github.com/johnpapa/angular-styleguide#style-y032) should be stored in a variable such as 'vm'.  

```
function View1Controller($scope) {

  this.title = "View 1";

}
```

would become 

```
function View1Controller($scope) {
  var vm = this;

  vm.title = "View 1";

}
```

I can make the changes and submit a pull request if you like :thumbsup:

**Comment by andyjessop** [comment]
Yep, that's great - please go ahead with the pull request.
